### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by darreneid** [Wizzerrd/DiscordClone#2]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `login` form should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `signup` and `login`.
- [x] Errors should clear when moving between `signup` and `login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `login` or `signup` forms
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The elements are positioned correctly on the page
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by Wizzerrd** [comment]
Render site ready for review

**Comment by darreneid** [comment]
- logging in as Demo User 2 is broken, gives me a 403 in the console
- when signing up, submitting form with combination of valid and invalid fields breaks error handling
- when signing up, link back to sign in needs to be styled
- 404 page should have a link back to home

**Comment by Wizzerrd** [comment]
1) I messed up the seeding for Demo 2 and will have to make a new commit to main and possibly take down the postrgresql server
2) I think I just fixed that will include a fix for the demo user in the commit for this fix
3) Working on getting my registration form to adopt styling from the login. It works but not always and I need to figure out why
4) Top left discord icon is a link to home. I can throw another link in there though
